# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftCoroutine_Utils_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftCoroutine_Utils_Demo
  pod 'SwiftCoroutine_Utils', :path => '..'

  target 'SwiftCoroutine_Utils_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
